name: 'My custom action'
description: 'Be a composite action'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      env:
        VA: ${{ github.action_repository }}
    
    - run: echo "${{ github.action_repository }}"
      shell: bash
      
    - run: echo "${{ env.GHAR }}"
      env:
        GHAR: ${{ github.action_repository }}
      shell: bash
